Fix view more text and get customizer working for view more link.
the-events-calendar/the-events-calendar pull request #3444
Opened 2021-02-11 15:01 UTC by Camwyn

As part of [ECP-568]

Convert the "view more" _widget_ link test to a filterable attribute - add one for the link and for the link title (for accessibility purposes)

Add customizer styling for the link that matches the work in https://github.com/the-events-calendar/events-pro/pull/1691

includes the common branch that fixes the customizer priority: https://github.com/the-events-calendar/tribe-common/pull/1547

2021-02-11 15:28 UTC, bordoni requested changes

2021-02-11 15:28 UTC, bordoni commented on src/Tribe/Views/V2/Views/Widgets/Widget_List_View.php
> +		return tribe_get_events_link();
This is a V1 method, we should avoid it.

2021-02-12 19:44 UTC, sc0ttkclark approved these changes

2021-02-12 20:32 UTC, sc0ttkclark approved these changes

2021-02-12 20:33 UTC, merged