Clean up Customizer logic
the-events-calendar/the-events-calendar pull request #3461
Opened 2021-02-22 11:24 UTC by alliuca

Description: Updates the bucket branch with the latest B21.02. Also cleans up the Customizer logic a bit, so that we re-use the tribe_events_single_view_v2_is_enabled function from the views provider file.

2021-02-23 03:51 UTC, paulmskim requested changes

2021-02-23 03:51 UTC, paulmskim commented on src/Tribe/Views/V2/Assets.php
> -		}
should we not be keeping this? we don't want to enqueue single event styles if it's not a single event page, nor do we want to enqueue if it's a block editor single right?

2021-02-23 03:51 UTC, paulmskim commented on src/functions/views/provider.php
> +	}
Oh I see, you moved the logic here. I don't think this should live here. If we needed to know if single view v2 is enabled but didn't care if it was a single event or if it had blocks or not, then this doesn't allow us to separate that logic. We should move it back to the assets file.

2021-03-15 15:19 UTC, bordoni approved these changes

2021-03-15 15:20 UTC, merged