TEC-383: List-style views > Avoid "Now Onwards" heading
the-events-calendar/the-events-calendar pull request #3515
Opened 2021-05-04 22:27 UTC by mitogh

Update the logic to render the upcoming label for the views using the current view uses a List type of view.

Artifact: https://d.pr/v/wBMaqn

2021-05-05 13:08 UTC, borkweb requested changes
Just a few minor text changes and then this is good to go once tests pass!

2021-05-05 13:08 UTC, borkweb commented on readme.txt
> +* Tweak - Adjust wording for 'onwards' for different scenarios on views using the List type of view [TEC-3831]
```suggestion
* Tweak - Reduced the usage of the word "onwards" on list-style view date range headings where simpler headings are better suited. [TEC-3831]
```

2021-05-07 15:20 UTC, Camwyn commented on src/Tribe/Views/V2/Views/Traits/List_Behavior.php
> +
```suggestion
```
Superfluous line?

2021-05-07 20:29 UTC, borkweb submitted a review, later dismissed
:+1: - after tests pass, at least.

2021-05-10 15:52 UTC, merged