Fixes from danish zip tests
the-events-calendar/the-events-calendar pull request #3609
Opened 2021-08-10 18:49 UTC by Camwyn

2021-08-11 10:20 UTC, paulmskim reviewed
Can we add a short description of what this is fixing + an artifact?

2021-08-11 10:20 UTC, paulmskim commented on src/resources/postcss/components/full/_search.pcss
> +	 * Theme Overrides - Twenty Seventeen
Twenty Twenty

2021-08-19 09:53 UTC, paulmskim requested changes
a couple small things, but looks good otherwise. also my eyes bleed from your color choices.

2021-08-19 09:53 UTC, paulmskim commented on src/resources/postcss/widgets/full/_events-list.pcss
> +			}
And remove the above:

```suggestion
			&,
			&:visited {
				color: var(--tec-color-link-accent);
			}
```

2021-08-19 09:53 UTC, paulmskim commented on src/resources/postcss/widgets/full/_events-list.pcss
> +			}
```suggestion
			&,
			&:visited {
				color: var(--tec-color-link-accent);
			}
```

2021-08-19 16:12 UTC, borkweb approved these changes

2021-08-19 16:13 UTC, merged