TEC-3992 Sharing Block Re-Skin
the-events-calendar/the-events-calendar pull request #3618
Opened 2021-08-18 12:36 UTC by EugeneKyale

Artifact : https://www.loom.com/share/7df920c8f69f41d185d684b753e94b67
Ticket : https://theeventscalendar.atlassian.net/browse/TEC-3992

2021-08-19 09:21 UTC, paulmskim requested changes
one small fix, also let's make sure we touch base with Avada.

2021-08-19 09:21 UTC, paulmskim commented on src/styles/event-links/frontend.pcss
> +}
same note on avada here.

2021-08-19 09:21 UTC, paulmskim commented on src/styles/event-links/frontend.pcss
> +			&::before {
```suggestion
			&:before {
```

2021-09-01 11:47 UTC, EugeneKyale commented
I'm closing this PR because we're using a different approach for this task. 
Reference : https://github.com/the-events-calendar/the-events-calendar/pull/3627

2021-09-01 11:47 UTC, closed without merging