[TEC-3330] Ensure the category archive event breadcrumb links to the main events page.
the-events-calendar/the-events-calendar pull request #3623
Opened 2021-08-25 11:45 UTC by EugeneKyale

Ticket : https://theeventscalendar.atlassian.net/browse/TEC-3330
Artifact : https://www.loom.com/share/e03a5756ae4749a5bbeaf7e692f166d1

2021-08-25 15:44 UTC, paulmskim requested changes

2021-08-25 15:44 UTC, paulmskim commented on src/views/v2/components/breadcrumbs/linked-breadcrumb.php
> +		href="<?php echo esc_url( tribe_get_events_link() ); ?>"
We should not be adjusting the template here. We set up the template variables in the BE, that's where we should be adjusting this value.

2021-08-26 17:13 UTC, bordoni submitted a review, later dismissed

2021-08-30 16:37 UTC, paulmskim approved these changes

2021-08-31 11:16 UTC, merged