Unescape the title more thoroughly
the-events-calendar/the-events-calendar pull request #3628
Opened 2021-09-01 15:34 UTC by Camwyn

Use html_entity_decode instead of htmlspecialchars_decode so that other special characters get unescaped as well.
Also fixed apostrophes in the page title.

This prevents anything else hooking into the_title from double-escaping characters.

All this gets escaped later, as seen below:
:camera: https://d.pr/v/vYJ7nJ

[TEC-4049]
[TEC-4058]

2021-09-02 17:28 UTC, skyshab requested changes

2021-09-02 17:28 UTC, skyshab commented on src/Tribe/Views/V2/View.php
> +		return html_entity_decode($title, ENT_QUOTES);
Space inside parentheses 

```suggestion
		return html_entity_decode( $title, ENT_QUOTES );
```

2021-09-03 17:01 UTC, EugeneKyale commented
Looks good, we only need a change log.

2021-09-03 17:04 UTC, EugeneKyale approved these changes

2021-09-03 20:46 UTC, merged