Feature/tec 3465 event status
the-events-calendar/the-events-calendar pull request #3673
Opened 2021-10-26 09:22 UTC by jesseeproductions

Adds the backend coding to handle the event status includes:

- Service Provider
- Meta Support
- Classic Editor Support
- Migration of reason field to a single field
- Automated Tests

Artifact: https://cloudup.com/c5w99UdhkSX

_Ref:_ [TEC-3465](https://theeventscalendar.atlassian.net/browse/TEC-3465)
_Ref:_ [TEC-3466](https://theeventscalendar.atlassian.net/browse/TEC-3466)
_Ref:_ [TEC-3468](https://theeventscalendar.atlassian.net/browse/TEC-3468)

2021-11-02 20:14 UTC, Camwyn requested changes
Really just some docblock tweaks - looks great 😄

2021-11-02 20:14 UTC, Camwyn commented on src/Tribe/Event_Status/Event_Status_Provider.php
> +	const DISABLED = 'TEC_EVENT_STATUS_DISABLED';
Docblock, something like 
```suggestion
	/**
	 * The constant used to disable event status.
	 */
	const DISABLED = 'TEC_EVENT_STATUS_DISABLED';
```

2021-11-02 20:14 UTC, Camwyn commented on src/Tribe/Event_Status/Models/Event.php
> +	 * @return string The event's status reason or empty string if none.
Empty string also if default 'scheduled' status.

2021-11-03 11:10 UTC, jesseeproductions commented on src/Tribe/Event_Status/Classic_Editor.php
> +		do_action( 'tribe_events_event_status_metabox_save', $post_id, $data );
I added one before that seemed to be the easiest place.

2021-11-04 17:45 UTC, Camwyn approved these changes
🎸

2021-11-04 17:48 UTC, merged