Feature/tec 4131 subscribe to calendar integration
the-events-calendar/the-events-calendar pull request #3702
Opened 2021-11-16 15:31 UTC by Camwyn

Integration of (and improvement on) the subscribe-to-calendar extension.

More performant: Removed js dependency - it can all be handled via CSS.
More modular: Split up into smaller objects and smaller templates.

2021-11-16 16:50 UTC, bordoni requested changes

2021-11-16 16:50 UTC, bordoni commented on src/Tribe/Views/V2/iCalendar/Links/Abstract_Link.php
> +		$view_url_args['tribe-bar-date'] = date( 'Y-m-d' ); // Subscribe from today.
`build_date_object` From Date Utils.

2021-11-16 16:50 UTC, bordoni commented on src/Tribe/Views/V2/iCalendar/Links/Google_Calendar.php
> +			'uri'   => static::get_gcal_uri( $view ),
Indent.

2021-11-16 16:50 UTC, bordoni commented on src/Tribe/Views/V2/iCalendar/Links/Google_Calendar.php
> +		$links[] = '<a class="tribe-events-gcal tribe-events-button" href="' . esc_url( static::get_gcal_uri( $view ) ) . '" title="' . esc_attr( $label ) . '">+ ' . esc_html( $label ) . '</a>';
Indentation

2021-11-16 16:50 UTC, bordoni commented on src/Tribe/Views/V2/iCalendar/Links/Abstract_Link.php
> +	}
Docblock.

2021-11-16 16:50 UTC, bordoni commented on src/Tribe/Views/V2/iCalendar/Links/Abstract_Link.php
> +abstract class Abstract_Link {
Lets create an interface for this too.

2021-11-18 17:23 UTC, Camwyn commented
Current tests are passing  - but they won't tomorrow. The snapshots contain dates.

2021-11-24 02:22 UTC, bordoni approved these changes

2021-11-24 15:20 UTC, merged