Remove the Amalgamator from Event Settings and deprecate the file.
the-events-calendar/the-events-calendar pull request #3707
Opened 2021-11-18 15:05 UTC by Camwyn

Also removes the call in Main.php to listen for the keyword and process.

📷 [Bad](blob:https://theeventscalendar.atlassian.net/c1d1b8bb-366c-574c-af91-e991888874d9) `blob:https://theeventscalendar.atlassian.net/c1d1b8bb-366c-574c-af91-e991888874d9`
📸 [Good](https://d.pr/i/0NxbMF)

2021-11-22 17:26 UTC, jesseeproductions reviewed
@Camwyn - Looks good, fix the readme conflict and good to go.

2021-11-24 19:34 UTC, Camwyn commented
@jesseeproductions can I get a re-review please? Updating dismissed your review.

2021-11-29 12:35 UTC, jesseeproductions approved these changes
@Camwyn Reapproved.

2021-11-29 20:03 UTC, bordoni requested changes
We have a depercated folder that we should use.

2021-11-29 20:03 UTC, bordoni commented on src/Tribe/Amalgamator.php
> +_deprecated_file( __FILE__, 'TBD', 'No replacement.' );
Move the file to the deprecated folder.

2021-11-29 20:33 UTC, Camwyn commented on src/Tribe/Amalgamator.php
> +_deprecated_file( __FILE__, 'TBD', 'No replacement.' );
Good call - thanks!

2021-11-29 20:34 UTC, bordoni submitted a review, later dismissed

2021-11-30 22:12 UTC, bordoni approved these changes

2021-11-30 22:18 UTC, merged