Ensure `tribe_this_week` shortcode plays well with month view caching. [ECP-967]
the-events-calendar/the-events-calendar pull request #3733
Opened 2021-12-16 15:40 UTC by EugeneKyale

This PR ensures the `tribe_this_week` shortcode respects the layout parameter when month view cache is enabled.

Ticket : https://theeventscalendar.atlassian.net/browse/ECP-967
Article : https://www.loom.com/share/59813bfb757c497a8a6431e7ae46d0b7

2022-01-04 19:30 UTC, Camwyn commented on src/Tribe/Views/V2/Views/Traits/HTML_Cache.php
> +		if ( is_a( $post, 'WP_Post' ) && has_shortcode( $post->post_content, 'tribe_this_week' ) ) {
```suggestion
		if ( $post instanceof WP_Post && has_shortcode( $post->post_content, 'tribe_this_week' ) ) {
```

2022-01-04 20:01 UTC, bordoni requested changes

2022-01-04 20:01 UTC, bordoni commented on src/Tribe/Views/V2/Views/Traits/HTML_Cache.php
> +		}
This code is to support something in the Pro Shortcodes, we need to move it to the Pro codebase and utilize the `tribe_events_views_v2_should_cache_html` filter to allow third party developers to modify it. The hook i mentioned here already exists.

2022-01-05 15:45 UTC, EugeneKyale commented
This has been moved to ECP on this [PR](https://github.com/the-events-calendar/events-pro/pull/1873).

2022-01-05 15:45 UTC, closed without merging