Update links visible property (renamed from "display")
the-events-calendar/the-events-calendar pull request #3746
Opened 2022-01-17 20:24 UTC by Camwyn

and filter the return value of is_visible() to allow easier show/hide toggling.

[TEC-4214]

:camera: https://d.pr/v/TSGAqP

2022-01-24 17:44 UTC, Camwyn commented
Force push to move some code to a separate branch.

2022-02-01 17:41 UTC, bordoni requested changes

2022-02-01 17:50 UTC, Camwyn commented on src/Tribe/Views/V2/Views/Traits/iCal_Data.php
> +		$display_ical = apply_filters( "tribe_events_{$this->slug}_show_ical_link", $display_ical );
🤦🏼

2022-02-02 00:07 UTC, bordoni approved these changes

2022-02-02 00:07 UTC, bordoni commented on src/Tribe/Views/V2/Views/Traits/iCal_Data.php
> +			[$display_ical],
Spacing

2022-02-02 15:12 UTC, bordoni approved these changes

2022-02-02 15:13 UTC, merged