Resolve Theme bleeding styles for Buttons and Titles
the-events-calendar/the-events-calendar pull request #3782
Opened 2022-02-21 20:53 UTC by bordoni

2022-02-22 16:56 UTC, Camwyn requested changes

2022-02-22 16:56 UTC, Camwyn commented on src/resources/postcss/views/full/day/_event.pcss
> +		@mixin event-title-link;
swap the order - for all three

2024-03-28 04:49 UTC, bordoni commented
Ship it!

2024-03-28 14:45 UTC, Camwyn approved these changes

2024-03-29 02:37 UTC, merged