Correct the logic to ensure all subscribe link hooks get set up immediately.
the-events-calendar/the-events-calendar pull request #3832
Opened 2022-05-03 13:51 UTC by Camwyn

[TEC-4313]
:movie-camera: https://d.pr/v/v8ryc3

2022-05-04 15:48 UTC, stratease submitted a review, later dismissed
Looks good!

2022-05-05 09:20 UTC, lucatume approved these changes

2022-05-05 09:24 UTC, lucatume requested changes
The test snapshots need updating or fixing.
Remember to run `composer install --no-dev` in Common before doing that.

2022-05-17 15:31 UTC, bordoni approved these changes

2022-05-17 15:34 UTC, merged