Add Outlook Subscribe to Calendar Views and Outlook Export with updated design to Single Events.
the-events-calendar/the-events-calendar pull request #3839
Opened 2022-05-16 10:36 UTC by jesseeproductions

Adds subscribe links for Outlook 365 and Outlook Live to Calendar Views
Adds export links for Outlook 365 and Outlook Live to Single Events
Updates the template for single events export template to use the dropdown from the calendar views.

Artifact:
https://www.figma.com/file/N4mXr5KuVHVSZoJ6kcIiaO/TEC-Products-Design-System?node-id=4693%3A19157

Tickets
_Ref:_ [TEC-4168](https://theeventscalendar.atlassian.net/browse/TEC-4168)
_Ref:_ [TEC-4176](https://theeventscalendar.atlassian.net/browse/TEC-4176)

2022-05-16 20:17 UTC, Camwyn submitted a review, later dismissed

2022-05-17 21:15 UTC, bordoni requested changes

2022-05-17 21:15 UTC, bordoni commented on src/Tribe/Views/V2/iCalendar/Single_Events.php
> +		$this->template = $template;
Create a method like `get_template()`

2022-05-18 03:57 UTC, bordoni approved these changes

2022-05-18 17:40 UTC, Camwyn requested changes
Some small cleanup on the pcss
That abstract class should really be a Trait
Other stuff is more comments

2022-05-18 17:40 UTC, Camwyn commented on src/views/v2/components/subscribe-links/single-event-list.php
> +				<?php $this->template( 'components/icons/cal-export', [ 'classes' => [ 'tribe-events-c-subscribe-dropdown__export-icon' ] ] ); ?>
This is not working for me locally (the icon)

2022-05-19 10:30 UTC, jesseeproductions commented on src/resources/postcss/components/full/_ical-link.pcss
> +			width: 217px;
It is full width otherwise.

2022-05-19 10:30 UTC, jesseeproductions commented on src/Tribe/Views/V2/iCalendar/Links/Outlook_Abstract_Export.php
> +abstract class Outlook_Abstract_Export extends Link_Abstract {
Changed to a trait as the classes do not need to override anything currently in the outlook abstract class.

2022-05-19 10:42 UTC, jesseeproductions commented on src/resources/postcss/components/full/_ical-link.pcss
> +	.tribe-events {
correct

2022-05-24 14:25 UTC, Camwyn approved these changes
Looks great!

2022-05-24 14:25 UTC, Camwyn commented on readme.txt
> -<<<<<<< HEAD
Nice catch! 😊

2022-05-24 15:32 UTC, merged