Fix aggregator csv
the-events-calendar/the-events-calendar pull request #3876
Opened 2022-06-16 19:22 UTC by Camwyn

[TEC-4070]

1. Ensure that import continues when we're in the admin: https://d.pr/i/TxrEif

2022-06-20 17:11 UTC, bordoni requested changes

2022-06-20 17:11 UTC, bordoni commented on src/Tribe/Aggregator/Cron.php
> +		$date .= sprintf(':%02d', $minutes) . ':00';
Spacing.

2022-06-20 17:11 UTC, bordoni commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> -		}
Let's make sure it doesn't show on all pages.

2022-06-21 15:12 UTC, Camwyn commented on src/Tribe/Aggregator/Cron.php
> +		$date .= sprintf(':%02d', $minutes) . ':00';
```suggestion
		$date .= sprintf( ':%02d', $minutes ) . ':00';
```

2022-06-22 15:26 UTC, bordoni approved these changes

2022-06-23 12:51 UTC, merged