Feature/tec 4493 rest params
the-events-calendar/the-events-calendar pull request #3995
Opened 2022-09-26 17:34 UTC by moraleida

(copy of #3990, rebased oustide of strudel)

By default, unless the site administrator has filtered the
tribe_events_rest_use_inclusive_start_end_dates filter to return a
falsy value, a REST API request for the /events endpoint will cast the
start_date parameter to the start of the day, and the end_date
parameter to the end of the day.

This adds a strict_dates supported REST API argument to allow REST API
clients to control, in the context of a request, the default value of
the value filtered in the
tribe_events_rest_use_inclusive_start_end_dates filter.

The filtered value will still override this value if explicitly set.

Furthermore, I've fixed the description of the end_date parameter: it
will limit the fetch by Events ending before a date and time; it's not
about the start date.

Artifacts: tests

[TEC-4493](https://theeventscalendar.atlassian.net/browse/TEC-4493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)

2022-09-28 23:19 UTC, stratease approved these changes
Groovy

2022-09-29 09:38 UTC, lucatume requested changes
Just missing documentation in the archive endpoing `READ_args` method.

2022-09-29 09:38 UTC, lucatume commented on src/Tribe/REST/V1/Endpoints/Archive_Event.php
> +		'starts_before' => 'starts_before',
Add argument documentation for these parameters in he `READ_args` method of this class.

2022-09-29 13:42 UTC, rafsuntaskin submitted a review, later dismissed

2022-09-29 13:43 UTC, rafsuntaskin commented
`restv1` tets are still failing.

2022-09-29 14:08 UTC, moraleida commented
oh, that's new... looking into it

2022-09-29 18:39 UTC, moraleida commented
finally! :tada:

2022-09-30 08:24 UTC, lucatume approved these changes

2022-09-30 12:25 UTC, merged