Fix CT1 Builder::first method type check
the-events-calendar/the-events-calendar pull request #4030
Opened 2022-11-01 13:35 UTC by lucatume

Ticket: [ECP-1402](https://theeventscalendar.atlassian.net/browse/ECP-1402)

Artifacts:
* the code is already covered by tests in TEC
* an additional test has been [added to ECP to cover this](https://github.com/the-events-calendar/events-pro/pull/2109)

This adds type-checking to the `Builder::first` method to make sure the returned type will be either the Model one or `null`.

2022-11-01 21:13 UTC, stratease requested changes
Minor tweak.

2022-11-01 21:13 UTC, stratease commented on src/Events/Custom_Tables/V1/Models/Builder.php
> +				return is_array( $result ) ? array_values( $result ) : null;
Should update return doc too, like:
```
* @return Model|null|array
```

2022-11-02 04:17 UTC, bordoni submitted a review, later dismissed

2022-11-02 15:49 UTC, stratease submitted a review, later dismissed

2022-11-03 09:55 UTC, lucatume commented
I've updated this PR to make sure the Custom Tables v1 queries will play nice with WordPress 6.1 caching of queries

2022-11-03 15:17 UTC, stratease submitted a review, later dismissed

2022-11-07 10:07 UTC, merged