Ensure that when we hit a single-event ical endpoint we get a the correct single event.
the-events-calendar/the-events-calendar pull request #4076
Opened 2022-12-05 20:28 UTC by Camwyn

[TEC-4469]

2022-12-05 20:53 UTC, Camwyn commented on src/Tribe/Views/V2/iCalendar/Request.php
>  		$view_slug = $this->context->get( 'view', 'default' );
More:
It will return the default view (for me, locally, that's Month) and _not_ `single-event`

2022-12-05 21:29 UTC, stratease approved these changes

2022-12-06 00:04 UTC, stratease approved these changes

2022-12-06 00:04 UTC, stratease commented on src/Tribe/Views/V2/iCalendar/Request.php
>  		$view_slug = $this->context->get( 'view', 'default' );
Can we add tests for the failure situation?

2022-12-06 01:46 UTC, bordoni requested changes

2022-12-06 01:46 UTC, bordoni commented on src/Tribe/Service_Providers/Context.php
> +								if ( 1 === (int) tribe_get_request_var( 'ical', 0 ) && is_singular( TEC::POSTTYPE) ) {
```suggestion
								if ( 1 === (int) tribe_get_request_var( 'ical', 0 ) && is_singular( TEC::POSTTYPE ) ) {
```

2022-12-06 15:39 UTC, bordoni approved these changes

2022-12-06 15:42 UTC, merged