Add title tag to Google Maps iframes. [TEC-4243]
the-events-calendar/the-events-calendar pull request #4078
Opened 2022-12-06 17:00 UTC by EugeneKyale

Ticket : [TEC-4243](https://theeventscalendar.atlassian.net/browse/TEC-4243)

Adding title tag attribute to Google Maps iframes to improve accessibility.

**Artifact 📸** 

![image](https://user-images.githubusercontent.com/22029087/205974174-c308fd00-e58a-482e-ab53-7443c2f71bcd.png)

2023-01-09 17:00 UTC, EugeneKyale commented
@Camwyn I've added a snapshot test for this as we discussed earlier. Please let me know if the coverage is sufficient.

2023-01-09 18:18 UTC, Camwyn requested changes
This looks good but the test needs some tweaking. The test result does not include a venue title in the iframe title attribute.

2023-01-09 18:18 UTC, Camwyn commented on tests/views_integration/Tribe/Events/Views/Modules/__snapshots__/Map_BasicTest__test_render_google_maps_iframe_with_mock_data__1.php
> +  title="Google maps iframe displaying the address to "
This is not adding the venue title - we should ensure that it's passed or findable for the test.

2023-01-24 15:01 UTC, Camwyn approved these changes

2023-01-24 15:12 UTC, merged