Modified single-event.php to use tribe_get_formatted_cost instead of tribe_get_cost
the-events-calendar/the-events-calendar pull request #4101
Opened 2023-01-11 17:44 UTC by sdokus

2023-01-11 20:31 UTC, borkweb requested changes
Good change! Just a small tweak to the changelog entry and an ultra-tiny spacing change 🕺

2023-01-11 20:31 UTC, borkweb commented on readme.txt
> +* Fix - Modified single-event.php to use tribe_get_formatted_cost instead of tribe_get_cost.
```suggestion
= [TBD] TBD =

* Fix - Modified single-event.php to use tribe_get_formatted_cost instead of tribe_get_cost. [TEC-4652]
```

2023-01-11 20:31 UTC, borkweb commented on src/views/single-event.php
> +$cost = tribe_get_formatted_cost( $event_id );
```suggestion
$cost  = tribe_get_formatted_cost( $event_id );
```

2023-02-16 02:03 UTC, bordoni commented
> @bordoni - can you see this over the finish line?

@EugeneKyale is making sure it's on the next Blue sprint.

2023-02-16 10:27 UTC, EugeneKyale commented
> > @bordoni - can you see this over the finish line?
> 
> @EugeneKyale is making sure it's on the next Blue sprint.

I'll take this over, thanks @sdokus and @bordoni

2023-02-16 13:21 UTC, EugeneKyale commented
@bordoni this is ready for a review.

2023-02-16 13:22 UTC, bordoni approved these changes

2023-02-16 13:23 UTC, merged