Fix/tec 4693 canonical tags improvements
the-events-calendar/the-events-calendar pull request #4168
Opened 2023-03-07 10:00 UTC by EugeneKyale

2023-03-07 16:53 UTC, Camwyn approved these changes

2023-03-08 05:36 UTC, bordoni submitted a review, later dismissed
New integrations should use the new system in `TEC/Events/Integrations` we already have a YoastSEO integration.

2023-03-08 10:50 UTC, EugeneKyale commented
> New integrations should use the new system in `TEC/Events/Integrartions` we already have a YoastSEO integration.

@bordoni I've made the updates to use the new integration system.

2023-03-08 18:02 UTC, Camwyn requested changes
One suggestion

2023-03-08 18:02 UTC, Camwyn commented on src/Events/Integrations/Plugins/Rank_Math/Provider.php
> +	}
Might be simpler:
```suggestion
	public function load_conditionals(): bool {
		return defined( 'RANK_MATH_FILE' ) && ! empty( RANK_MATH_FILE );
	}
```

2023-03-08 21:31 UTC, EugeneKyale commented on src/Events/Integrations/Plugins/Rank_Math/Provider.php
> +	}
@Camwyn thanks, this is better.

2023-03-21 20:25 UTC, Camwyn approved these changes

2023-03-22 09:41 UTC, merged