Venue Details on List View
the-events-calendar/the-events-calendar pull request #4183
Opened 2023-03-16 13:01 UTC by EugeneKyale

Ticket: [TEC-4731](https://theeventscalendar.atlassian.net/browse/TEC-4731)

Ensures the venue country is displayed in the list view when venues are created through the block editor interface.

**Screenshot 📸**

![image](https://user-images.githubusercontent.com/22029087/225624698-511d3444-8e85-4830-8371-3e0b1e0b6275.png)

[TEC-4731]: https://theeventscalendar.atlassian.net/browse/TEC-4731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-03-17 19:32 UTC, redscar submitted a review, later dismissed

2023-03-21 15:47 UTC, redscar submitted a review, later dismissed

2023-03-23 17:43 UTC, Camwyn requested changes
Just needs one more test.

2023-03-23 17:43 UTC, Camwyn commented on readme.txt
> -* Fix - Make improvements to the canonical tags added to event views to improve compatibility with SEO plugins. [TEC-4693]
Be  careful about this - in another PR you moved it to the top. We can move them during the deploy process (and avoid conflicts) 😉

2023-03-23 17:43 UTC, Camwyn commented on tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php
> -		100 Rue de Le Chat, Paris, Ile de France	</span>
Can we add a second test that includes a state/province as well? To be sure it doesn't get duplicated accidentally.

2023-03-27 18:19 UTC, Camwyn approved these changes

2023-03-27 18:19 UTC, Camwyn commented on tests/views_integration/Tribe/Events/Views/V2/Partials/List_View/Event/__snapshots__/VenueTest__test_render_with_event_with_venue__1.php
> -		100 Rue de Le Chat, Paris, Ile de France	</span>
:doh:

2023-03-27 18:25 UTC, merged