Added link to trash wiki page.
the-events-calendar/the-events-calendar pull request #4221
Opened 2023-04-21 01:13 UTC by stratease

2023-04-21 01:43 UTC, bordoni requested changes

2023-04-21 01:43 UTC, bordoni commented on src/admin-views/tribe-options-general.php
> +		__( 'Trashed events will permanently be deleted in %1$d days, you can change that value using <code>%2$s</code>. <a href="%3$s" target="_blank">Read more.</a>', 'the-events-calendar' ),
Make sure to add ` rel="noopener noreferrer"`

2023-04-21 16:34 UTC, lucatume approved these changes

2023-04-24 00:49 UTC, bordoni approved these changes

2023-04-24 15:57 UTC, merged