Ensure we have a <dt> before every <dd> for valid HTML
the-events-calendar/the-events-calendar pull request #4269
Opened 2023-05-22 14:06 UTC by Camwyn

Simple fix for the issue, might require a bit more conversation before it goes live.

[BTRIA-1847]

2023-05-22 19:46 UTC, redscar submitted a review, later dismissed

2023-05-23 19:05 UTC, bordoni requested changes
Changelog, and update the docblock with the TBD version.

2023-05-26 14:04 UTC, Camwyn commented on src/views/modules/meta/venue.php
> +		<dt style="display:none;"><?php // This element is just to make sure we have a valid HTML ?></dt>
More accessible version of this?

2023-05-26 14:05 UTC, Camwyn commented on src/views/modules/meta/organizer.php
> +				<dt class="tribe-organizer-url-label"><?php echo esc_html( $website_title ) ?></dt>
Make this more accessible if $website_title is empty?

2023-05-26 14:08 UTC, Camwyn commented on src/views/modules/meta/venue.php
> +		<dt style="display:none;"><?php // This element is just to make sure we have a valid HTML ?></dt>
```suggestion
		<dt class="tribe-common-a11y-visual-hide">Venue information</dt>
```

2023-05-26 14:10 UTC, Camwyn commented on src/views/modules/meta/venue.php
> +			<dt class="tribe-venue-url-label"> <?php echo esc_html( $website_title ) ?> </dt>
same as above

2023-05-26 14:10 UTC, Camwyn commented on src/views/modules/meta/venue.php
> +			<dt style="display:none;"><?php // This element is just to make sure we have a valid HTML ?></dt>
same as above

2023-07-25 18:13 UTC, Camwyn commented
This is covered by Eugene's PR https://github.com/the-events-calendar/the-events-calendar/pull/4329

2023-07-25 18:13 UTC, closed without merging