Enhancement/btria 1908
the-events-calendar/the-events-calendar pull request #4314
Opened 2023-06-30 19:47 UTC by andrasguseo

Add filter and logic to handle the saving of additional data for Organizers and Venues when doing a CSV import.

2023-07-17 14:01 UTC, Camwyn requested changes
Some docblock tweaks, otherwise 👨🏼‍🍳

2023-07-17 14:01 UTC, Camwyn commented on src/Tribe/Importer/File_Importer_Venues.php
> +				 * On save the metakey gets the "_Venue" prefix. It should be removed before the import.
```suggestion
				 * On save the metakey gets the "_Venue" prefix added. So it should be removed before the import.
```

2023-07-21 08:22 UTC, andrasguseo commented on src/Tribe/Importer/File_Importer_Organizers.php
> +		 */
Good learning, thanks!

2023-07-21 08:30 UTC, andrasguseo commented
@Camwyn Thanks for the code review and the feedback. So much appreciated!
There was a conflict in the readme because a release went out since the branch was created. I "tried" to resolve it, please check if I did it correctly. Thanks again!

2023-08-18 18:55 UTC, Camwyn commented
This is scheduled to go out in Sprint 32 (we're currently on 29) I'll keep it up to date until then. Self-assigning

2023-08-18 20:37 UTC, andrasguseo commented
Awesome, thanks @Camwyn !

2024-11-27 08:18 UTC, andrasguseo commented
This was handled in two other PRs, so closing it.
* https://github.com/the-events-calendar/the-events-calendar/pull/4702
* https://github.com/the-events-calendar/the-events-calendar/pull/4738

2024-11-27 08:18 UTC, closed without merging