Fix for nonces being cached on some views.
the-events-calendar/the-events-calendar pull request #4409
Opened 2023-10-24 15:39 UTC by stratease

2023-11-01 09:27 UTC, EugeneKyale submitted a review, later dismissed

2023-11-01 13:30 UTC, Camwyn requested changes
Small readme tweak

2023-11-01 13:30 UTC, Camwyn commented on readme.txt
> +* Fix - On the Past Events View, the nonce was incorrectly being generated twice, and one of them would be cached in our HTML transient cache. This was causing a 401 nonce errors to occur when the ca
```suggestion
* Fix - On the Past Events View, the nonce was incorrectly being generated twice, and one of them would be cached in our HTML transient cache. This was causing a 401 nonce errors to occur when the cached nonce expired. The nonce generation was moved outside the HTML generation that is being cached. [TEC-4936]
```

2023-11-02 18:06 UTC, Camwyn approved these changes

2023-11-02 19:16 UTC, merged