Fix/tec 4974 missing closing li tags
the-events-calendar/the-events-calendar pull request #4427
Opened 2023-11-08 09:50 UTC by andrasguseo

[TEC-4974]

* The closing </li> tags are missing for the items in the Table on Contents on the General and Display settings pages.
* Added 2 filters to allow filtering the TOC contents. This can be helpful when adding settings sections, for example for an extension.

2024-05-28 22:01 UTC, andrasguseo commented
@bordoni This is an older one. Main probably needs to be pulled in for an update.

2024-05-29 01:47 UTC, bordoni requested changes
Lets avoid change formatting on the whole file, make the changes only on the `<li>` and to the filter.

Move the spacing changes to a separate PR.

Also would love to revisit that actual filter names to be a bit more verbose

2024-05-29 01:47 UTC, bordoni commented on src/admin-views/tribe-options-general.php
> +$tec_events_general_toc = apply_filters( 'tec_events_general_settings_toc', $tec_events_general_toc );
The docblock needs a `@since` and use `@param` folr filters, no need to filter into the variable, than apply the addition. Do it all in one line.

2024-05-29 01:47 UTC, bordoni commented on src/admin-views/tribe-options-display.php
> +$tec_events_display_toc = apply_filters( 'tec_events_display_settings_toc', $tec_events_display_toc );
The docblock needs a `@since` and use `@param` folr filters, no need to filter into the variable, than apply the addition. Do it all in one line.

2024-05-30 10:32 UTC, andrasguseo commented
@bordoni I did an interactive rebase (with the help of chatGPT) to remove the code formatting commits. If there's a better way to do it, I'd love to know.
Addressed your comments.
Also happy to talk about hook naming conventions.

2024-06-01 03:11 UTC, bordoni requested changes
A couple of things:
* Update the title of the PR to be more descriptive
* Release branch needs to be `release/T24.asag`
* Make sure we are not commits changes to `common` submodule.

2024-06-01 03:11 UTC, bordoni commented on src/admin-views/tribe-options-general.php
> + * @var array $tec_events_display_toc Array of items of the TOC.
```suggestion
 * @param array $tec_events_display_toc Array of items of the TOC.
```

2024-06-01 03:11 UTC, bordoni commented on src/admin-views/tribe-options-display.php
> + * @var array $tec_events_display_toc Array of items of the TOC.
```suggestion
 * @param array $tec_events_display_toc Array of items of the TOC.
```

2024-06-03 11:21 UTC, andrasguseo commented
@bordoni 

> Make sure we are not commits changes to common submodule.

Not sure how common files got in the mix. I'd like to know how this could have happened and how I can avoid it in the future. Also, I need help removing them. Thx.

2024-06-19 19:55 UTC, bordoni approved these changes

2024-06-20 07:40 UTC, merged