Enhancing docblock information and adding missing tags
the-events-calendar/the-events-calendar pull request #4593
Opened 2024-05-17 03:33 UTC by Sjaure

### 🎫 Ticket

[TICKET_ID]

### 🗒️ Description

### 🎥 Artifacts 

### ✔️ Checklist
- [ ] Changelog entry in the `readme.txt` file.
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [ ] Check the base branch for your PR.
- [ ] Add your PR to the project board for the release.

2024-05-18 03:41 UTC, bordoni requested changes

2024-05-18 03:41 UTC, bordoni commented on src/functions/template-tags/link.php
> + * @param bool|string $anchor (optional) The link text. Use %title% to place the post title in your string. Default is false
Make sure this is addressed.

2024-05-18 03:42 UTC, bordoni commented
Add the `Code Review` label and assign yourself.

2024-05-29 00:01 UTC, Sjaure commented
@bordoni , I added the missing tag, assigned it to myself. Also added the missing punctuation and comments on readme.txt
I guess someone else needs to merge the changes to that file or should I go ahead and resolve it?

2024-06-03 23:08 UTC, Sjaure commented
@bordoni, I fixed a couple of issues with the changelog file and resolved the conflicts too.

2024-06-08 01:04 UTC, bordoni requested changes

2024-06-08 01:04 UTC, bordoni commented on readme.txt
> +>>>>>>> release/T24.asag
Resolve the conflict.

2024-06-12 03:52 UTC, bordoni commented
Move to `release/T24.babayaga`

2024-08-08 15:13 UTC, closed without merging