DocBlock: `tec_views_v2_subscribe_link_visibility()`
the-events-calendar/the-events-calendar pull request #4604
Opened 2024-05-30 11:26 UTC by andrasguseo

Tweak to the `tec_views_v2_subscribe_link_visibility()` and `tec_views_v2_subscribe_link_' . self::get_slug() . '_visibility()` docBlocks to add more details.

2024-06-01 03:05 UTC, bordoni approved these changes

2024-06-01 03:06 UTC, bordoni requested changes
Point it to the correct branch.

2024-06-13 17:52 UTC, codingmusician approved these changes

2024-06-19 19:52 UTC, bordoni approved these changes

2024-06-24 20:40 UTC, dpanta94 approved these changes

2024-06-24 20:41 UTC, merged