Past Events shortcode attribute
the-events-calendar/the-events-calendar pull request #4652
Opened 2024-07-04 23:39 UTC by pattihis

### 🎫 Ticket

[TEC-1805]

### 🗒️ Description
A shortcode attribute of past=”yes” for the [tribe_events] shortcode to display past events. 

[Related PR](https://github.com/the-events-calendar/events-pro/pull/2501)

### ✔️ Checklist
- [ ] Changelog entry in the `readme.txt` file.
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [x] Check the base branch for your PR.
- [x] Add your PR to the project board for the release.

2024-07-05 20:00 UTC, pattihis commented
Closing in favour of https://github.com/the-events-calendar/events-pro/pull/2503

2024-07-05 21:38 UTC, pattihis commented
needed for the time being, restoring.

2024-07-10 11:06 UTC, rafsuntaskin requested changes

2024-07-10 11:06 UTC, rafsuntaskin commented on .github/workflows/tests-php.yml
> +          ${SLIC_BIN} wp core update --force --version=6.3.1
WP 6.3.1 is too old, the other plugins are using `6.4.1` so at least we should try to match that.

2024-07-10 11:39 UTC, rafsuntaskin approved these changes

2024-07-10 13:36 UTC, merged