Ensure we don't try to enqueue nonexistent override stylesheets.
the-events-calendar/the-events-calendar pull request #4680
Opened 2024-07-24 20:33 UTC by Camwyn

[ECP-1811]

2024-07-25 16:19 UTC, Camwyn commented on src/Tribe/Assets.php
> +		// Custom stylesheet
```suggestion
		// Custom stylesheet.
```

2024-07-29 17:05 UTC, rafsuntaskin approved these changes

2024-07-29 17:06 UTC, dpanta94 requested changes

2024-07-29 17:06 UTC, dpanta94 commented on src/Tribe/Assets.php
> +		_deprecated_function( __METHOD__, '6.6.0', 'Tribe__Events__Assets::should_enqueue_frontend' );
```suggestion
		_deprecated_function( __METHOD__, '6.6.1', 'Tribe__Events__Assets::should_enqueue_frontend' );
```

2024-07-29 17:06 UTC, redscar approved these changes

2024-07-29 17:07 UTC, dpanta94 approved these changes

2024-07-29 17:08 UTC, merged