Improve docblocks for `tribe_get_event_website_link` function and fil…
the-events-calendar/the-events-calendar pull request #4753
Opened 2024-09-14 01:38 UTC by Sjaure

…ters

### 🎫 Ticket

[TICKET_ID]

### 🗒️ Description

### 🎥 Artifacts 

### ✔️ Checklist
- [ ] Ran `npm run changelog` to add changelog file(s). More info [here](https://docs.theeventscalendar.com/developer/git/changelogs/#process)
- [ ] Code is covered by **NEW** `wpunit` or `integration` tests.
- [ ] Code is covered by **EXISTING** `wpunit` or `integration` tests.
- [ ] Are all the **required** tests passing?
- [ ] Automated code review comments are addressed.
- [ ] Have you added Artifacts?
- [ ] Check the base branch for your PR.
- [ ] Add your PR to the project board for the release.

2024-09-16 14:32 UTC, codingmusician submitted a review, later dismissed

2024-09-16 14:33 UTC, Camwyn requested changes
I think these two need a bit more info.

2024-09-16 14:33 UTC, Camwyn commented on src/functions/template-tags/link.php
> + * @param null|object|int $event  The event object or ID. Defaults to null.
```suggestion
 * @param null|object|int $event  The event object or ID. Defaults to null - which will use global `$post`.
```

2024-09-16 14:33 UTC, Camwyn commented on src/functions/template-tags/link.php
> + * @param string          $target Optional. The target attribute for the link. Defaults to '_self'.
```suggestion
 * @param string          $target Optional. The target attribute for the link. Defaults to '_self'. Allowed values are: '_self', '_blank', '_parent', '_top', '_unfencedTop'.
```

2024-09-16 20:58 UTC, Sjaure commented on src/functions/template-tags/link.php
> + * @param null|object|int $event  The event object or ID. Defaults to null.
Done @Camwyn

2024-09-16 20:58 UTC, Sjaure commented on src/functions/template-tags/link.php
> + * @param string          $target Optional. The target attribute for the link. Defaults to '_self'.
Done

2024-09-17 19:11 UTC, Camwyn approved these changes

2024-09-17 19:14 UTC, merged