Fixing nav styling and behavior.
the-events-calendar/the-events-calendar pull request #4787
Opened 2024-10-29 19:02 UTC by Camwyn

WIP - fixing the tab styles and behavior. Particularly on smaller screens.

2024-11-04 02:54 UTC, bordoni requested changes

2024-11-04 02:54 UTC, bordoni commented on src/resources/packages/wizard/components/tabs.tsx
> +		6: { id: "tickets", panelId: "ticketsPanel", title: "Tickets", disabled: true, completed: false, ref: useRef(null) }
Translations.

2024-11-04 02:54 UTC, bordoni commented on src/resources/packages/wizard/components/tabs/display/tab.tsx
> +		function(e) {
```suggestion
	(event) => {
```

would also change from `e.` to `event.` in here.

2024-11-04 02:54 UTC, bordoni commented on src/resources/packages/wizard/components/tabs/tab.tsx
> +		tabIndex={activeTab === index ? 0 : -1}
```suggestion
			aria-controls={tab.panelId}
			aria-selected={activeTab === index}
			className="tec-events-onboarding__tab-button"
			disabled={tab.disabled}
			id={tab.id}
			onClick={handleClick}
			ref={tab.ref}
			role="tab"
			tabIndex={activeTab === index ? 0 : -1}
```

2024-11-04 02:54 UTC, bordoni commented on src/resources/packages/wizard/components/tabs/tickets/inputs/ticket-install.tsx
> +				{__("Yes, install Event Tickets for free on my website.", "the-events-calendar")}
```suggestion
					{__("Yes, install Event Tickets for free on my website.", "the-events-calendar")}
```

2024-11-04 02:54 UTC, bordoni commented on src/resources/packages/wizard/components/tabs/welcome/inputs/opt-in.js
> +				<a href="#" target="_blank">What permissions are being granted?</a>
Language.

2024-11-06 21:17 UTC, Camwyn commented on package.json
> +    "react-router-dom": "^6.10.0",
Don't recall adding these?

2024-11-06 21:17 UTC, Camwyn commented on .gitignore
> +src/build
don't commit any build files!

2024-12-10 20:39 UTC, closed without merging